/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package arrayShift;

import java.util.Arrays;

public class ArrayShift {

    public int[] arrayShift(int[] inputArray, int value){

        int[] outputArray = new int[inputArray.length + 1];

        if(inputArray.length == 0){
            return new int[]{value};
        }

        int middleIndex;

        if((inputArray.length % 2) == 0){
           middleIndex = (outputArray.length / 2); //no +1
        }
        else{
            middleIndex = (int) Math.floor(outputArray.length / 2);
        }

        for(int i = 0; i < outputArray.length; i++){
            if(i == middleIndex){
                outputArray[i] = value;
            }
            else if(i < middleIndex){
                outputArray[i] = inputArray[i];
            }
            else{
                outputArray[i] = inputArray[i - 1];
            }
        }

        return outputArray;
    }
}
